name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Reemplaza "main" con el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Puedes ajustar la versión de Node.js según tus necesidades

    - name: Build and Deploy
      run: |
        npm install # O ejecuta los comandos necesarios para construir tu proyecto
        npm run build # Reemplaza con el comando de construcción de tu proyecto
        git config --global user.email "jironjuarezjuan@hotmail.com"
        git config --global user.name "Juan Carlos"
        git checkout --orphan gh-pages
        git --work-tree build add --all
        git --work-tree build commit -m "GitHub Pages Deployment"
        git push origin HEAD:gh-pages --force
      env:
        CI: true
